# **Topic 2. 배열 생성하고 다루기_실습**

## **(1) 실습문제**

### 1) 실습1 : Numpy 라이브러리 로딩
* Numpy 라이브러리를 np 별칭을 붙여 로딩하시오.

In [ ]:
# 라이브러리 불러오기
import numpy as np

### 2) 실습2 : 배열 만들기

* 다음의 데이터로 배열을 생성하시오.
    * 배열 a : [10, 11, 12, 13, 14, 15]
    * 배열 b : [[11, 12, 13, 14], [15, 16, 17, 18], [19, 20, 21, 22]]

In [ ]:
# 배열 a 생성
a = np.array([10, 11, 12, 13, 14, 15])
print(a)

[10 11 12 13 14 15]


In [ ]:
# 배열 b 생성
b = np.array([[11, 12, 13, 14], [15, 16, 17, 18], [19, 20, 21, 22]])
print(b)

[[11 12 13 14]
 [15 16 17 18]
 [19 20 21 22]]


### 3) 실습3 : 배열 속성 확인
* 실습2에서 생성한 배열a, b에 대해 다음의 정보를 조회하시오.
    * 차원의 수(ndim)
    * 크기(shape)

In [ ]:
# 배열 a의 속성
print(a.ndim)
print(a.shape)

1
(6,)


In [ ]:
# 배열 b의 속성
print(b.ndim)
print(b.shape)

2
(3, 4)


### 4) 실습4 : 배열 형태 변환

* 다음의 조건대로 배열의 형태를 변경하시오.
    * 배열 a : (3,2)
    * 배열 b : (4,3)

In [ ]:
# 배열 a : (3,2)
a.reshape(3,2)

array([[10, 11],
       [12, 13],
       [14, 15]])

In [ ]:
# 배열 b : (4,3)
np.reshape(b, (4,3))

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19],
       [20, 21, 22]])